  
name: ive_flutter_core
description: Core assets for InnoVet Europe Flutter projects
# version: 1.2.6f
version: 1.2.11
homepage: https://www.harriercentral.com/
publish_to: none

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: ^3.38.3

dependencies:
  flutter:
    sdk: flutter

  flutter_spinkit: ^5.2.2 
  freezed_annotation: ^3.1.0
  freezed: ^3.2.3
  intl: ^0.20.2
  json_annotation: ^4.9.0
  photo_view: ^0.15.0 
  qr_flutter: 4.1.0 
  
dependency_overrides:
  analyzer: ^8.4.1
  
dev_dependencies:
  build_runner: ^2.9.0
  json_serializable: ^6.11.3

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  
  uses-material-design: true

  fonts:

    - family: AvenirNextDemiBold
      fonts:
        - asset: fonts/AvenirNextDemiBold.ttf
        - asset: fonts/AvenirNextDemiBoldItalic.ttf
          style: italic

